# Site settings
title: Jong10 in Wonderland
#email:
description: > # this means to ignore newlines until "baseurl:"
  "Jongyeol's programming blog."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jong10.com" # the base hostname & protocol for your site
#twitter_username: jong10
#github_username:  jongyeol

# Build settings
markdown: kramdown
